const currencies = [
    { code: 'USD', name: 'United States Dollar' },
    { code: 'EUR', name: 'Euro' },
    { code: 'JPY', name: 'Japanese Yen' },
    { code: 'GBP', name: 'British Pound Sterling' },
    { code: 'AUD', name: 'Australian Dollar' },
    { code: 'CAD', name: 'Canadian Dollar' },
    { code: 'CHF', name: 'Swiss Franc' },
    { code: 'CNY', name: 'Chinese Yuan' },
    { code: 'SEK', name: 'Swedish Krona' },
    { code: 'NZD', name: 'New Zealand Dollar' },
    { code: 'MXN', name: 'Mexican Peso' },
    { code: 'SGD', name: 'Singapore Dollar' },
    { code: 'HKD', name: 'Hong Kong Dollar' },
    { code: 'NOK', name: 'Norwegian Krone' },
    { code: 'KRW', name: 'South Korean Won' },
    { code: 'TRY', name: 'Turkish Lira' },
    { code: 'RUB', name: 'Russian Ruble' },
    { code: 'INR', name: 'Indian Rupee' },
    { code: 'BRL', name: 'Brazilian Real' },
    { code: 'ZAR', name: 'South African Rand' },
    { code: 'PLN', name: 'Polish Zloty' },
    { code: 'IDR', name: 'Indonesian Rupiah' },
    { code: 'THB', name: 'Thai Baht' },
    { code: 'MYR', name: 'Malaysian Ringgit' },
    { code: 'PHP', name: 'Philippine Peso' },
    { code: 'CZK', name: 'Czech Koruna' },
    { code: 'ILS', name: 'Israeli Shekel' },
    { code: 'HUF', name: 'Hungarian Forint' },
    { code: 'AED', name: 'United Arab Emirates Dirham' },
    { code: 'ARS', name: 'Argentine Peso' },
    { code: 'CLP', name: 'Chilean Peso' },
    { code: 'COP', name: 'Colombian Peso' },
    { code: 'DKK', name: 'Danish Krone' },
    { code: 'EGP', name: 'Egyptian Pound' },
    { code: 'NGN', name: 'Nigerian Naira' },
    { code: 'PKR', name: 'Pakistani Rupee' },
    { code: 'SAR', name: 'Saudi Riyal' },
    { code: 'BDT', name: 'Bangladeshi Taka' },
    { code: 'VND', name: 'Vietnamese Dong' },
    { code: 'QAR', name: 'Qatari Riyal' },
    { code: 'UAH', name: 'Ukrainian Hryvnia' },
    { code: 'BGN', name: 'Bulgarian Lev' },
    { code: 'HRK', name: 'Croatian Kuna' },
    { code: 'RON', name: 'Romanian Leu' },
    { code: 'PEN', name: 'Peruvian Sol' },
    { code: 'MAD', name: 'Moroccan Dirham' },
    { code: 'ISK', name: 'Icelandic Krona' },
    { code: 'JMD', name: 'Jamaican Dollar' },
    { code: 'KES', name: 'Kenyan Shilling' },
    { code: 'KZT', name: 'Kazakhstani Tenge' },
    { code: 'LKR', name: 'Sri Lankan Rupee' },
    { code: 'TWD', name: 'New Taiwan Dollar' },
    { code: 'DZD', name: 'Algerian Dinar' },
    { code: 'BHD', name: 'Bahraini Dinar' },
    { code: 'KWD', name: 'Kuwaiti Dinar' },
    { code: 'OMR', name: 'Omani Rial' },
    { code: 'TND', name: 'Tunisian Dinar' }
    // Add more currencies as needed
  ];
  
  export default currencies;